### ISSUE TITLE
default_access_token config key is exlcuded

### ISSUE THREAD

**Issue by unstoppablecarl** [schimpanz/Laravel-Facebook#1]
the config key `default_access_token` is excluded when injecting config. It should be added to this array to work.

https://github.com/schimpanz/facebook/blob/master/src/FacebookFactory.php#L57

It should not be required, but it should not be excluded either.

**Comment by vinkla** [comment]
How would we go about fixing this? Maybe you could submit a PR?

**Comment by vinkla** [comment]
Done in 49f1cf1e3983655923995e86beb764ed66853dcf
