### ISSUE TITLE
FacebookSDKException in FacebookCurlHttpClient.php line 83

### ISSUE THREAD

**Issue by iaroel** [schimpanz/Laravel-Facebook#3]
Hi,
I'm trying to get the feed of a user like 
````php
$response = Facebook::get('/zuck/feed?fields=id,message&limit=5');

print_r($response);
````
But I'm getting this error.
Failed to connect to graph.facebook.com port 443: Network is unreachable
Can you please advice if I'm doing something wrong?
The website is running on a local ubuntu server as virtual host the address is something like http://domainname.com.dev

Thanks in advance.

**Comment by vinkla** [comment]
Hi @iaroel, can't really say what the problem is but have you tried running your GET query in the [Graph API Explorer](https://developers.facebook.com/tools/explorer)?

**Comment by iaroel** [comment]
Hi Vincent,

Thanks for quick reply.
I've tried with API explorer with another user "not zuck" and it returned the user name and the id.
I suppose it's working but I'm still getting the same error on my Laravel app.

**Comment by vinkla** [comment]
That is strange. Maybe it could be something with your environment. Are you sure everything is [setup correctly](https://github.com/schimpanz/Laravel-Facebook#installation)?

**Comment by iaroel** [comment]
Yep,

I think I've done it all correctly.
I've allso tried the nmap to make sure that my server is able to reach the facebook url like 
nmap -p 443 graph.facebook.com and it looks like it is reachable.

here is my config file:
````
return [


    'default' => 'main',

   

    'connections' => [

        'main' => [
            'app_id' => 'myidhere',
            'app_secret' => 'mysecrethere',
            'default_graph_version' => 'v2.4',
            //'default_access_token' => null,
        ],

        'alternative' => [
            'app_id' => 'your-app-id',
            'app_secret' => 'your-app-scret',
            'default_graph_version' => 'v2.4',
            //'default_access_token' => null,
        ],

    ],

];
````

Also added following lines to app.php:
````
'providers' => [
....
Schimpanz\Facebook\FacebookServiceProvider::class,
....
]
````
 'aliases' => [
....
'Facebook' => Schimpanz\Facebook\Facades\Facebook::class,
....
]
````

**Comment by vinkla** [comment]
Sounds like an outgoing firewall/proxy/network issue. You should be able to verify that using `ping` and `curl` from the machine where your website runs. Don't know much about nmap but try ping and curl.

**Comment by iaroel** [comment]
I've disabled the firewall but didn't work.

Thanks for your time.

**Comment by vinkla** [comment]
What if you try setting up the application outside your environment?

**Comment by iaroel** [comment]
Yep I was planning to do that.
Will create new a virtual machine and try.

Thank you.

**Comment by vinkla** [comment]
(Y) let me know how it goes!

**Comment by iaroel** [comment]
Hi Vincent,

It turns out it was an ipv6 issue.
I've tried to add 
````
curl_setopt( $ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 );
````
to /vendor/facebook/webdriver/lib/net/URLChecker.php and /vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php but it didn't work.

So I've pinged graph.facebook.com and current ip was 173.252.88.66 hope they won't decide to change it soon :) and added:
````
173.252.88.66    graph.facebook.com
````
to my /etc/hosts file so far it looks like working but I'm aware this is a very dodgy solution.
I'll test on live server too and hopping live server supports ipv6.

Thanks

**Comment by vinkla** [comment]
Good that you've solved it! Maybe open an issue at Facebooks PHP repository with this same question?

**Comment by iaroel** [comment]
Yep, good thinking.

**Comment by vinkla** [comment]
Yeah, it could be something with their package or maybe something we have missed to add in this one. Let me know if you find anything else!
