### ISSUE TITLE
How to get the access token?

### ISSUE THREAD

**Issue by cse031sust02** [schimpanz/Laravel-Facebook#4]

**Comment by vinkla** [comment]
Pleas provide more information. What are you trying to achieve?

**Comment by cse031sust02** [comment]
Sorry! I managed to get the access token. It would be much helpful if you can add an example of how user will login to facebook using this package.
Also is there any way to set the access token like 'vinkla/instagram' package, so that we do not need to add it in every api call?

https://github.com/vinkla/instagram#examples
We can set the access token once
Instagram::setAccessToken($data);

**Comment by vinkla** [comment]
Yeah, you can set it in the configuration with `default_access_token `.
